title: Brice Loose # your name (or website title) here
logo: "/images/headshot.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Associate Professor
  URI [Graduate School of Oceanography](https://web.uri.edu/gso/)
  URI [Department of Ocean Engineering](https://web.uri.edu/engineering/about/ocean-engineering/)
  Narragansett, RI 02882
  <br><br>
  [Geotracerkitchen.org](http://geotracerkitchen.org)
  <br><br>
  <a href="https://bloose.github.io">Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
