title: Brice Loose # your name (or website title) here
logo: "/images/headshot.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Associate Professor
  URI <a href="https://web.uri.edu/gso/"> Graduate School of Oceanography</a>
  URI <a href="https://web.uri.edu/engineering/about/ocean-engineering/">Department of Ocean Engineering</a>
  Narragansett, RI 02882
  <br><br>
  <a href="http://geotracerkitchen.org">Geotracerkitchen.org></a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
